# Generated by Django 6.0.6 on 2026-06-09 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tutors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tutorcertification',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='tutors.tutorprofile'),
        ),
        migrations.AddField(
            model_name='availability',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='tutors.tutorprofile'),
        ),
        migrations.AddField(
            model_name='tutorverificationdocument',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_documents', to='tutors.tutorprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='availability',
            unique_together={('tutor', 'day_of_week', 'start_time')},
        ),
    ]
