# Generated by Django 4.2.30 on 2026-07-09 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayMentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('paypal', 'PayPal'), ('stripe', 'Stripe')], max_length=20)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='tutorprofile',
            name='years_of_experience',
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='education',
            field=models.JSONField(blank=True, help_text='List of education entries', null=True),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='experience',
            field=models.JSONField(blank=True, help_text='List of experience entries', null=True),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='tutors', to='tutors.subject'),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='payment_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutor_profile', to='tutors.paymentinfo'),
        ),
    ]
