# Generated by Django 4.2.30 on 2026-07-09 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0003_paymentinfo_remove_tutorprofile_years_of_experience_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorprofile',
            old_name='teaching_mode',
            new_name='session_status',
        ),
    ]
