# Generated by Django 4.2.30 on 2026-07-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0004_rename_teaching_mode_tutorprofile_session_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='tutor_banners/'),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='language',
            field=models.CharField(blank=True, help_text='Primary language of instruction', max_length=50),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Contact number for students', max_length=20),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='professional_title',
            field=models.CharField(blank=True, help_text='e.g. Math Tutor, Physics Instructor', max_length=100),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='tutor_profiles/'),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='skills',
            field=models.JSONField(blank=True, help_text='List of skills or expertise areas', null=True),
        ),
    ]
