# Generated by Django 4.2.30 on 2026-07-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0005_tutorprofile_banner_tutorprofile_language_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorprofile',
            name='subjects',
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='subjects',
            field=models.JSONField(blank=True, help_text='List of all Subjects', null=True),
        ),
    ]
