# Generated by Django 4.2.30 on 2026-08-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0006_remove_tutorprofile_subjects_tutorprofile_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorprofile',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Hourly rate in USD', max_digits=10),
        ),
    ]
