# Generated by Django 4.2.30 on 2026-08-04 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0007_alter_tutorprofile_hourly_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availability',
            old_name='is_blocked',
            new_name='is_booked',
        ),
    ]
