# Generated by Django 4.2.30 on 2026-08-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0008_rename_is_blocked_availability_is_booked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='day_of_week',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=9),
        ),
    ]
