# Generated by Django 4.2.30 on 2026-08-04 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tutors', '0009_alter_availability_day_of_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinfo',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_info', to=settings.AUTH_USER_MODEL),
        ),
    ]
