# Generated by Django 5.0.14 on 2026-08-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0010_paymentinfo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='payouts_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='stripe_connect_account_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
