# Generated by Django 5.0.14 on 2026-08-08 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatthread',
            name='initial_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
