# Generated by Django 5.0.14 on 2026-08-08 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatthread_initial_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatthread',
            name='initial_message',
        ),
    ]
