# Generated by Django 5.0.14 on 2026-08-08 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_chatthread_tutor'),
        ('tutors', '0010_paymentinfo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatthread',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_threads_as_tutor', to='tutors.tutorprofile'),
        ),
    ]
