# Generated by Django 5.0.14 on 2026-08-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
