# Generated by Django 5.0.14 on 2026-08-20 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_booking_student_acknowledged_booking_tutor_completed'),
        ('wallets', '0005_alter_withdrawal_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.booking'),
        ),
    ]
