# Generated by Django 5.0.14 on 2026-08-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_booking_student_acknowledged_booking_tutor_completed'),
        ('wallets', '0006_withdrawal_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='sessions',
            field=models.ManyToManyField(blank=True, related_name='withdrawals', to='bookings.booking'),
        ),
    ]
