# Generated by Django 5.0.14 on 2026-08-20 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0007_withdrawal_sessions'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='account_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='account_number',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='bank_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
