# Generated by Django 5.0.14 on 2026-08-22 17:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0008_withdrawal_account_name_withdrawal_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='withdrawable_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
