# Generated by Django 6.0.6 on 2026-06-09 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('online', 'Online'), ('onsite', 'Onsite')], max_length=20)),
                ('scheduled_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Student notes or special requests')),
                ('tutor_response_note', models.TextField(blank=True, help_text='Tutor reason for decline/acceptance')),
                ('session_link', models.URLField(blank=True, help_text='Online session link if applicable')),
                ('location_address', models.TextField(blank=True, help_text='Onsite session address')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-scheduled_date', '-start_time'],
            },
        ),
    ]
