# Generated by Django 4.2.30 on 2026-08-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_options_booking_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='subject',
            field=models.CharField(blank=True, help_text='Subject for the tutoring session', max_length=100, null=True),
        ),
    ]
