# Generated by Django 4.2.30 on 2026-08-05 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0010_paymentinfo_user'),
        ('bookings', '0004_alter_booking_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='availability_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='tutors.availability'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='scheduled_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
