# Generated by Django 5.0.14 on 2026-08-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_availability_slot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
    ]
