# Generated by Django 5.0.14 on 2026-08-18 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_googleoauthtoken_socialaccount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='session_link',
        ),
        migrations.AddField(
            model_name='booking',
            name='google_event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
