# Generated by Django 5.0.14 on 2026-08-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_remove_booking_session_link_booking_google_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='session_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
