# Generated by Django 5.0.14 on 2026-08-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_booking_session_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='student_acknowledged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='tutor_completed',
            field=models.BooleanField(default=False),
        ),
    ]
