# Generated by Django 5.0.14 on 2026-08-22 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_booking_student_acknowledged_booking_tutor_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='tutor_has_withdrawn',
            field=models.BooleanField(default=True),
        ),
    ]
