# Generated by Django 5.0.14 on 2026-08-22 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_booking_tutor_has_withdrawn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='tutor_has_withdrawn',
            field=models.BooleanField(default=False),
        ),
    ]
